### ISSUE TITLE
New fluviewer conda environment complaining about missing pip

### ISSUE THREAD

**Issue by jpalmer37** [BCCDC-PHL/fluviewer-nf#10]
`
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
`

Should be a simple fix, despite being low priority.

**Comment by dfornika** [comment]
Interesting, I hadn't seen that. Feel free to bundle that in with another PR, I don't think this one needs a separate PR necessarily.
